### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by almereyda** [joeyb/collaborative-markdown#5]
The demo is currently not working.

Next to https://github.com/segmentio/socrates, this is one of the only MarkDown editors that I know of that are capable fo real time (OT) collaboration like Etherpad Lite.

Does that work?

**Comment by joeyb** [comment]
What was the issue that you were seeing with the demo? I just pulled it up and it seems to still be working.

**Comment by almereyda** [comment]
http://boiling-ocean-9398.herokuapp.com/ was just loading very slowly for me.
Now it seems to work, but only from different locations in Central Europe. I will have to check from home again.
It can be your heroku-plan is just a low-priority one.

Nice to see how easily it works, though.
