### ISSUE TITLE
Frontend not working

### ISSUE THREAD

**Issue by hacfi** [joeyb/collaborative-markdown#6]
When I run `node server.js` and open the browser at http://localhost:3000/ the page loads forever (eventuall timing out) and nothing shows up except in the stdout from node:

```
Unhandled document message: { v: 1,
  data:
   { title: 'New Document',
     markdown: '',
     id: '252010ed-def8-43c1-bfc8-ed75f40e8e64' },
  type: 'http://sharejs.org/types/JSONv0',
  m: { mtime: 1417471062649, ctime: 1417471062649 },
  c: null,
  d: null }
```

Any idea how I can get this running? Would love to give this app a try locally!!

I’m on OS X 10.9.5 with latest node.js (v0.10.33) and mongodb v2.6.

**Comment by almereyda** [comment]
I can confirm this behaviour also on Ubuntu 14.04 with Redis and Mongo from stock repositories.

**Comment by hacfi** [comment]
I’m not that experienced with debugging a DerbyJS app..any hint why this could fail now?

**Comment by almereyda** [comment]
Did you run Redis and MongoDB in advance?

**Comment by hacfi** [comment]
@almereyda I did..I’m starting to debug the issue now. If I don’t get it running on OS X I’ll try an older version of Ubuntu.

**Comment by hacfi** [comment]
Can’t solve this..some version conflict or so. I leave the issue open so others can see it might not work anymore.

**Comment by hacfi** [comment]
I don’t think there is an easy way to fix this so I’m closing the issue.
